#!/command/with-contenv bash

chown -R abc:abc "$EFB_DATA_PATH";

CONFIG_FILE="$EFB_DATA_PATH/profiles/$EFB_PROFILE/config.yaml";
if [ ! -f "$CONFIG_FILE" ]; then
    echo "File $CONFIG_FILE does not exists.";
    exit 1;
fi
