version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Shanghai"

  - package-ecosystem: "pip"
    directory: "/app"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Asia/Shanghai"
