#!/usr/bin/with-contenv bash

echo "Starting bot."

if [ $EFB_VERBOSE ]; then
    exec s6-setuidgid abc ehforwarderbot --profile $EFB_PROFILE -v
else
    exec s6-setuidgid abc ehforwarderbot --profile $EFB_PROFILE
fi
